### ISSUE TITLE
How to add streamlit secrets

### ISSUE THREAD

**Issue by jovyinny** [nyandajr/Afya_Check#3]
Can you provide the way to add the secret as the implementation need openAI's api key

**Comment by nyandajr** [comment]
Hello. I have added that can you check it?
Sent from Proton Mail mobile

-------- Original Message --------

**Comment by nyandajr** [comment]
Hello Bro. Just to clarify you want me to provide a way to add secret keys? is that what you meant?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by jovyinny** [comment]
There is a part on `initialize_openai` function where you kind of retrieve the secret key. Below is the function

```python
def initialize_openai():
    openai.api_key = st.secrets["general"]["my_api_key"]

```

This is the part i'd like get help with as i could not set the api key so had to use the version without GPT-3 functionality

**Comment by nyandajr** [comment]
For Local development you'd set the Environment variable
Setting up the Environment Variable:

Assuming your on Windows
- Open the start menu, type in "Environment Variables," then choose "Edit the system environment variables."
- In the System Properties window, click the “Environment Variables” button.
- Under the "User variables" section, click "New" and add the variable name as MY_API_KEY and the value as your actual OpenAI API key.
- Click OK, and OK again to save the changes.

Then you'd modify the function as

import os

def initialize_openai():
openai.api_key = os.environ["MY_API_KEY"]
------- Original Message -------

**Comment by jovyinny** [comment]
Oukay, I get it. 

Would the use of `.env` be best choice as most of project use this as conventional way of storing some environment variables.

**Comment by nyandajr** [comment]
Yes, Absolutely. Actually am migrating the app into flask and that is how I handle the API using the .env file.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by jovyinny** [comment]
That's cool. I can see there is a Pull request with flask implementation
